//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Personel
    {
        public int id { get; set; }

        [Display(Name="Departman Adý")]
        [Required(ErrorMessage ="Lüfen Bir Departman Seçiniz")]
        public Nullable<int> Departmanid { get; set; }
        [Required(ErrorMessage = "Ad Alaný Girmek Zorunludur")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyad Alaný Girmek Zorunludur")]
        public string Soyad { get; set; }

        [Display(Name="Maaþ")]
        [Required(ErrorMessage = "Maaþ Alaný Girmek Zorunludur")]
        [Range(1399,8000,ErrorMessage = "Maaþýnýz 1400-8000 Arasýnda Olmak Zorundadýr!!")]
        public Nullable<short> Maas { get; set; }

        [Display(Name="Doðum Tarihi")]
        [Required(ErrorMessage ="Lütfen Doðum Tarihinizi Seçiniz")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Required(ErrorMessage = "Lütfen Cinsiyetinizi Seçiniz")]
        public bool Cinsiyet { get; set; }

        [Display(Name="Evlilik Durumu")]
        public bool Evlimi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
